# config 配置
config:
  enableLog: true # 允许输出配置日志

# log 日志
log:
  level: debug
  development: true    # 开发模式
  enableGrpcLog: false # 允许输出grpc log

# opentracing 链路跟踪
opentracing:
  sampler:
    type: const
    param: 1
  reporter:
    logSpans: true
    localAgentHostPort: 127.0.0.1:6831

# mysql 
mysql:
  dsn: user:password@tcp(127.0.0.1:3306)/example?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4&clientFoundRows=true
  enableLog: true
  enableOpentracing: true

redis:
  mode: NormalDsn # redis客户端模式
  dsn: "redis://:foobared@127.0.0.1:6379/0"
  password: foobared
  db: 0 # 数据库index
  connectTimeout: 3s
  readTimeout: 3s
  writeTimeout: 3s
  sentinel:
    addrs: [127.0.0.1:16379,127.0.0.1:16380,127.0.0.1:16381]
    master_name: mymaster
    password: foobared
    connect_timeout: 3s
    read_timeout: 3s
    write_timeout: 3s
  mutex_expiry: 5s # 互斥锁过期时间

# pprof 性能分析
pprof:
  enable: false