# config 配置
config:
  enableLog: true # 允许输出配置日志

# log 日志
log:
  level: debug
  development: true    # 开发模式
  enableGrpcLog: false # 允许输出grpc log

# opentracing 链路跟踪
opentracing:
  sampler:
    type: const
    param: 1
  reporter:
    logSpans: true
    localAgentHostPort: 127.0.0.1:6831

# mysql 
mysql:
  dsn: user:password@tcp(127.0.0.1:3306)/example?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4&clientFoundRows=true
  enableLog: true
  enableOpentracing: true

# pprof 性能分析
pprof:
  enable: false