// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/flamefatex/grpc-gateway-example/model"
)

func newExample(db *gorm.DB, opts ...gen.DOOption) example {
	_example := example{}

	_example.exampleDo.UseDB(db, opts...)
	_example.exampleDo.UseModel(&model.Example{})

	tableName := _example.exampleDo.TableName()
	_example.ALL = field.NewAsterisk(tableName)
	_example.Id = field.NewInt64(tableName, "id")
	_example.Uuid = field.NewString(tableName, "uuid")
	_example.Name = field.NewString(tableName, "name")
	_example.Type = field.NewInt32(tableName, "type")
	_example.Description = field.NewString(tableName, "description")
	_example.CreateTime = field.NewTime(tableName, "create_time")
	_example.UpdateTime = field.NewTime(tableName, "update_time")

	_example.fillFieldMap()

	return _example
}

type example struct {
	exampleDo exampleDo

	ALL         field.Asterisk
	Id          field.Int64
	Uuid        field.String
	Name        field.String
	Type        field.Int32
	Description field.String
	CreateTime  field.Time
	UpdateTime  field.Time

	fieldMap map[string]field.Expr
}

func (e example) Table(newTableName string) *example {
	e.exampleDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e example) As(alias string) *example {
	e.exampleDo.DO = *(e.exampleDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *example) updateTableName(table string) *example {
	e.ALL = field.NewAsterisk(table)
	e.Id = field.NewInt64(table, "id")
	e.Uuid = field.NewString(table, "uuid")
	e.Name = field.NewString(table, "name")
	e.Type = field.NewInt32(table, "type")
	e.Description = field.NewString(table, "description")
	e.CreateTime = field.NewTime(table, "create_time")
	e.UpdateTime = field.NewTime(table, "update_time")

	e.fillFieldMap()

	return e
}

func (e *example) WithContext(ctx context.Context) IExampleDo { return e.exampleDo.WithContext(ctx) }

func (e example) TableName() string { return e.exampleDo.TableName() }

func (e example) Alias() string { return e.exampleDo.Alias() }

func (e *example) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *example) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 7)
	e.fieldMap["id"] = e.Id
	e.fieldMap["uuid"] = e.Uuid
	e.fieldMap["name"] = e.Name
	e.fieldMap["type"] = e.Type
	e.fieldMap["description"] = e.Description
	e.fieldMap["create_time"] = e.CreateTime
	e.fieldMap["update_time"] = e.UpdateTime
}

func (e example) clone(db *gorm.DB) example {
	e.exampleDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e example) replaceDB(db *gorm.DB) example {
	e.exampleDo.ReplaceDB(db)
	return e
}

type exampleDo struct{ gen.DO }

type IExampleDo interface {
	gen.SubQuery
	Debug() IExampleDo
	WithContext(ctx context.Context) IExampleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IExampleDo
	WriteDB() IExampleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IExampleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IExampleDo
	Not(conds ...gen.Condition) IExampleDo
	Or(conds ...gen.Condition) IExampleDo
	Select(conds ...field.Expr) IExampleDo
	Where(conds ...gen.Condition) IExampleDo
	Order(conds ...field.Expr) IExampleDo
	Distinct(cols ...field.Expr) IExampleDo
	Omit(cols ...field.Expr) IExampleDo
	Join(table schema.Tabler, on ...field.Expr) IExampleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IExampleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IExampleDo
	Group(cols ...field.Expr) IExampleDo
	Having(conds ...gen.Condition) IExampleDo
	Limit(limit int) IExampleDo
	Offset(offset int) IExampleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IExampleDo
	Unscoped() IExampleDo
	Create(values ...*model.Example) error
	CreateInBatches(values []*model.Example, batchSize int) error
	Save(values ...*model.Example) error
	First() (*model.Example, error)
	Take() (*model.Example, error)
	Last() (*model.Example, error)
	Find() ([]*model.Example, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Example, err error)
	FindInBatches(result *[]*model.Example, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Example) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IExampleDo
	Assign(attrs ...field.AssignExpr) IExampleDo
	Joins(fields ...field.RelationField) IExampleDo
	Preload(fields ...field.RelationField) IExampleDo
	FirstOrInit() (*model.Example, error)
	FirstOrCreate() (*model.Example, error)
	FindByPage(offset int, limit int) (result []*model.Example, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IExampleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetById(id int64) (result *model.Example, err error)
	DeleteById(id int64) (rowsAffected int64, err error)
	GetByUuid(uuid string) (result *model.Example, err error)
	DeleteByUuid(uuid string) (rowsAffected int64, err error)
	Query(uuid string, name string) (result []*model.Example, err error)
}

// SELECT * FROM @@table WHERE id = @id
func (e exampleDo) GetById(id int64) (result *model.Example, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM example WHERE id = ? ")

	var executeSQL *gorm.DB
	executeSQL = e.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// DELETE FROM @@table WHERE id = @id
func (e exampleDo) DeleteById(id int64) (rowsAffected int64, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("DELETE FROM example WHERE id = ? ")

	var executeSQL *gorm.DB
	executeSQL = e.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	rowsAffected = executeSQL.RowsAffected
	err = executeSQL.Error

	return
}

// SELECT * FROM @@table WHERE uuid = @uuid
func (e exampleDo) GetByUuid(uuid string) (result *model.Example, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, uuid)
	generateSQL.WriteString("SELECT * FROM example WHERE uuid = ? ")

	var executeSQL *gorm.DB
	executeSQL = e.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// DELETE FROM @@table WHERE uuid = @uuid
func (e exampleDo) DeleteByUuid(uuid string) (rowsAffected int64, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, uuid)
	generateSQL.WriteString("DELETE FROM example WHERE uuid = ? ")

	var executeSQL *gorm.DB
	executeSQL = e.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	rowsAffected = executeSQL.RowsAffected
	err = executeSQL.Error

	return
}

// SELECT * FROM @@table
// WHERE
// {{ if uuid != "" }} uuid = @uuid AND {{ end }}
// {{ if name != "" }} name LIKE %@name% AND {{ end }}
// 1=1
func (e exampleDo) Query(uuid string, name string) (result []*model.Example, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM example WHERE ")
	if uuid != "" {
		params = append(params, uuid)
		generateSQL.WriteString("uuid = ? AND ")
	}
	if name != "" {
		params = append(params, name)
		generateSQL.WriteString("name LIKE %?% AND ")
	}
	generateSQL.WriteString("1=1 ")

	var executeSQL *gorm.DB
	executeSQL = e.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (e exampleDo) Debug() IExampleDo {
	return e.withDO(e.DO.Debug())
}

func (e exampleDo) WithContext(ctx context.Context) IExampleDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e exampleDo) ReadDB() IExampleDo {
	return e.Clauses(dbresolver.Read)
}

func (e exampleDo) WriteDB() IExampleDo {
	return e.Clauses(dbresolver.Write)
}

func (e exampleDo) Session(config *gorm.Session) IExampleDo {
	return e.withDO(e.DO.Session(config))
}

func (e exampleDo) Clauses(conds ...clause.Expression) IExampleDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e exampleDo) Returning(value interface{}, columns ...string) IExampleDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e exampleDo) Not(conds ...gen.Condition) IExampleDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e exampleDo) Or(conds ...gen.Condition) IExampleDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e exampleDo) Select(conds ...field.Expr) IExampleDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e exampleDo) Where(conds ...gen.Condition) IExampleDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e exampleDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IExampleDo {
	return e.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (e exampleDo) Order(conds ...field.Expr) IExampleDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e exampleDo) Distinct(cols ...field.Expr) IExampleDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e exampleDo) Omit(cols ...field.Expr) IExampleDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e exampleDo) Join(table schema.Tabler, on ...field.Expr) IExampleDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e exampleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IExampleDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e exampleDo) RightJoin(table schema.Tabler, on ...field.Expr) IExampleDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e exampleDo) Group(cols ...field.Expr) IExampleDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e exampleDo) Having(conds ...gen.Condition) IExampleDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e exampleDo) Limit(limit int) IExampleDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e exampleDo) Offset(offset int) IExampleDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e exampleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IExampleDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e exampleDo) Unscoped() IExampleDo {
	return e.withDO(e.DO.Unscoped())
}

func (e exampleDo) Create(values ...*model.Example) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e exampleDo) CreateInBatches(values []*model.Example, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e exampleDo) Save(values ...*model.Example) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e exampleDo) First() (*model.Example, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Example), nil
	}
}

func (e exampleDo) Take() (*model.Example, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Example), nil
	}
}

func (e exampleDo) Last() (*model.Example, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Example), nil
	}
}

func (e exampleDo) Find() ([]*model.Example, error) {
	result, err := e.DO.Find()
	return result.([]*model.Example), err
}

func (e exampleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Example, err error) {
	buf := make([]*model.Example, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e exampleDo) FindInBatches(result *[]*model.Example, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e exampleDo) Attrs(attrs ...field.AssignExpr) IExampleDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e exampleDo) Assign(attrs ...field.AssignExpr) IExampleDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e exampleDo) Joins(fields ...field.RelationField) IExampleDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e exampleDo) Preload(fields ...field.RelationField) IExampleDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e exampleDo) FirstOrInit() (*model.Example, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Example), nil
	}
}

func (e exampleDo) FirstOrCreate() (*model.Example, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Example), nil
	}
}

func (e exampleDo) FindByPage(offset int, limit int) (result []*model.Example, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e exampleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e exampleDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e exampleDo) Delete(models ...*model.Example) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *exampleDo) withDO(do gen.Dao) *exampleDo {
	e.DO = *do.(*gen.DO)
	return e
}
